spring:
  application:
    name: chat

  datasource:
    url: jdbc:postgresql://localhost:5432/chat-app
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
  servlet:
    context-path: /api/v1

app:
  jwt:
    secret: "bXktc3VwZXItc2VjcmV0LWtleS1teS1zdXBlci1zZWNyZXQta2V5LTEyMzQ1Ng=="
    expiry: 1440


